# Generated by Django 3.1.4 on 2021-03-05 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210305_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.companies'),
        ),
    ]
