# Generated by Django 3.1.4 on 2021-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20210305_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='category',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nationality',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='guest',
            name='passport',
            field=models.CharField(max_length=40),
        ),
    ]
