# Generated by Django 3.1.4 on 2021-03-05 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20210305_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guesthouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.DecimalField(decimal_places=0, max_digits=15)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('green_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.companies'),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_type', models.CharField(max_length=40)),
                ('meal_plan', models.CharField(max_length=40)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservations.guest')),
                ('inovice_no', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice', to='reservations.invoice')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservations.rooms')),
            ],
        ),
    ]
