# Generated by Django 3.1.4 on 2021-03-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20210305_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='green_tax',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tgst',
        ),
    ]
