# Generated by Django 3.1.4 on 2021-03-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20210305_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='service_charge',
        ),
    ]
