# Generated by Django 3.1.4 on 2021-03-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_remove_invoice_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(max_length=20),
        ),
    ]
