# Generated by Django 3.1.4 on 2021-03-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20210305_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='inovice_no',
        ),
        migrations.AddField(
            model_name='invoice',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='reservations.reservations'),
            preserve_default=False,
        ),
    ]
