# Generated by Django 3.1.4 on 2021-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20210305_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='registration_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
